[package]
name = "nanorand"
description = "A tiny, fast, zero-dep library for random number generation."
repository = "https://github.com/aspenluxxxy/nanorand-rs"
keywords = ["rand", "random", "no-std", "entropy"]
categories = ["algorithms", "no-std"]
readme = "README.md"
version = "0.3.0"
authors = ["aspen <luxx4x@protonmail.com>"]
edition = "2018"
license = "Zlib"

[features]
default = ["std", "wyrand", "pcg64"]
std = []
wyrand = []
pcg64 = []

[dev-dependencies]
criterion = { version = "0.3", features = ["real_blackbox"] }

[[bench]]
name = "randbench"
harness = false

[profile.bench]
lto = 'thin'
opt-level = 3
codegen-units = 1
