[package]
name = "nanorand"
description = "A tiny, fast, zero-dep library for random number generation."
repository = "https://github.com/aspenluxxxy/nanorand-rs"
keywords = ["rand", "random", "no-std", "entropy"]
categories = ["algorithms", "no-std"]
readme = "README.md"
version = "0.2.2"
authors = ["aspen <luxx4x@protonmail.com>"]
edition = "2018"
license = "Zlib"

[features]
default = ["std", "atomics", "ctor", "wyrand", "pcg64"]
std = []
atomics = []
wyrand = []
pcg64 = []
ctor = ["std", "atomics"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "randbench"
harness = false

[profile.bench]
lto = 'thin'
opt-level = 3
codegen-units = 1