name: "Run Tests"
on: [push, pull_request]
jobs:
  tests:
    name: "Test with Rust ${{ matrix.rust.version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "Install ${{ matrix.rust.version }} Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: "${{ matrix.rust.version }}"
      - name: Run 'cargo test'
        uses: actions-rs/cargo@v1
        with:
          args: "--features ${{matrix.rust.features}}"
          command: test
    strategy:
      matrix:
        rust:
          - version: stable
            features: getrandom
          - version: nightly
            features: chacha,getrandom
        os: [windows-latest, ubuntu-latest, macos-latest]
